apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: urlshortener
  labels:
    app: cassandra
spec:
  type: ClusterIP
  selector:
    app: cassandra
  ports:
    - port: 9042
      targetPort: 9042
      protocol: TCP
      name: cql
