apiVersion: v1
kind: Service
metadata:
  name: tokenservice
  namespace: urlshortener
spec:
  selector:
    app: tokenservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080