apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: urlshortener
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data-0/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc

  namespace: urlshortener
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi